### ISSUE TITLE
Inclusion to stackage

### ISSUE THREAD

**Issue by centromere** [grayjay/json-rpc-server#2]
Greetings,

Would you consider adding json-rpc-server and json-rpc-client to stackage?

**Comment by grayjay** [comment]
@centromere Thanks for the suggestion.  I'll try to look into adding the packages to Stackage in January.

**Comment by grayjay** [comment]
Sorry for the delay.  I added both packages to Stackage:

https://www.stackage.org/nightly-2018-06-06/package/json-rpc-client-0.2.5.0
https://www.stackage.org/nightly-2018-06-06/package/json-rpc-server-0.2.6.0
